# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88cbeb51bd8d9687a00ddde0945b4a4bdff011fe70222248722f396cab3a2c2c2c58547b7bfcdd41eacbf5adee2b4c9db609a05d15f3b9f071e4902ed242c24

test:
  secret_key_base: 9db30424cc5f013b1dc9fa59dd06f6403ccbd5a9a688b2f5ff212ade146c8ec046c1324c602700a0e1158e0ded3b74a4d3ccf4a03a11b9d3aaa7fcba15d45cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
